### ISSUE TITLE
Github-Action 무한 루프 해결

### ISSUE THREAD

**Issue by EeeasyCode** [EeeasyCode/nest-study#4]
test.yml 로직에서 test 커버리지 수치를 readme.md에 push 과정에서 지속적으로 push 이벤트 발생
-> 이로 인해, test.yml 의 github action이 무한 루프

**해결**

```
jobs:
  TEST:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[TEST] update test coverage') }}
```

if문을 추가하여 readme.md를 업데이트 시켜주는 commit message는 제외하고 실행시킴
